# Generated by Django 3.2.5 on 2021-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_hw', '0002_auto_20210706_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
